marketmate/urls.py
from django.urls import path,include
from django.conf.urls.static import static

# importing upload url from settings
from .settings import DEBUG,UPLOAD_ROOT,UPLOAD_URL

# importing urls
import listings.urls as listings_urls
import users.urls as users_urls
import api.urls.urls as api_urls
from .admin import urls as admin_urls

# importing view for resource not found
from .views import ResourceNotFoundView

# importing Home view
from .views import Home

urlpatterns = [
    path('admin/', include(admin_urls)),
    path('', Home.as_view(),name="home"),
    path('users/', include(users_urls)),
    path("listings/", include(listings_urls)),
    path("api/", include(api_urls)),
    path("404/",ResourceNotFoundView.as_view() ,name="404_not_found"),

]

# making static path available for the browser
if DEBUG:
    urlpatterns+= static(UPLOAD_URL,document_root=UPLOAD_ROOT)

users/urls.py
from django.urls import path

# importing my view
from .views import SignUpView,LoginView, UserView,CreateUserView
from marketmate.views import ResourceNotFoundView

urlpatterns = [
    path("sign-up/", SignUpView.as_view(),name="user_signup"),
    path("login/", LoginView.as_view(),name="user_login"),
    path("create/", UserView.as_view(),name="user_create"),
    path("create/<token>", UserView.as_view(),name="user_create_verify"),
    path("verify/<token>", CreateUserView.as_view(),name=""),
    path("create-session/", UserView.as_view(),name="user_create_session"),
    path("destroy-session/", UserView.as_view(),name="user_destroy_session"),
    path("profile/", UserView.as_view(),name="user_profile"),
    path("<id>/profile/", UserView.as_view(),name="user_other_profile"),
    path("profile/edit/", UserView.as_view(),name="user_edit_profile"),
    path("profile/update", UserView.as_view(),name="user_update_profile"),

    # for every path other than specified
    path("<path:unknown_path>", (ResourceNotFoundView.as_view()),name="unknown_path"),
]

users/models.py
# imports to generate a unique name for every upload
import os, uuid,time,datetime

from django.core.validators import FileExtensionValidator
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from marketmate.settings import UPLOAD_URL
from .manager import UserManager

# importing typing for type hinting
from typing import Any

# to generate a unique name for every upload
def generate_filename(instance:Any,filename:str)->str:
    ext=filename.split(".")[1]
    unique_name = f"image-{uuid.uuid4()}.{ext}"
    return os.path.join(f"{UPLOAD_URL}images/users/", unique_name)


def generate_unique_id()->str:
    id= f"{time.time()}-{uuid.uuid4()}"
    return id[:20]


class User(AbstractBaseUser,PermissionsMixin):

    # validate the file upload type
    image_file_validator = FileExtensionValidator(
        allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp'],
        message='Only image files (jpg, jpeg, png, gif, bmp) are allowed.'
    )

    id=models.CharField(default=generate_unique_id,unique=True,primary_key=True,
                        editable=False, max_length=255)
    name=models.CharField( max_length=100)
    email=models.CharField(max_length=254,unique=True,null=False)
    contact_no=models.CharField(max_length=15,null=True,default=None,)

    is_superuser=models.BooleanField(default=False)
    is_staff=models.BooleanField(default=False)
    is_active=models.BooleanField(default=True)

    profile_picture = models.ImageField(upload_to=generate_filename, max_length=350, null=True, default=None,
                                      validators=[image_file_validator],blank=True)

    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    USERNAME_FIELD="email"
    REQUIRED_FIELDS=["name"]

    # to delete the previous image, if any
    def save(self,*args:Any, **kwargs:Any)->None:
        if self.id:
            previous_instance=User.objects.filter(id=self.id).first()
            # deleting only if a new image is uploaded
            if self.profile_picture and previous_instance.profile_picture and self.profile_picture!=previous_instance.profile_picture:
                previous_instance.profile_picture.delete()
            super().save(*args, **kwargs)

    # to initialize objects as user manager
    objects=UserManager()

    class Meta:
        db_table="user"

        def __str__(self) -> str:
            return self.name
        
class VerificationTokens(models.Model):
    name=models.CharField(null=False,default=None,max_length=50)
    email=models.CharField(null=False,max_length=50)
    token=models.CharField(null=False,max_length=50)
    created_at=models.DateTimeField(default=datetime.datetime.now)

users/forms.py
from django import forms
from .models import User


# Login form for the user
class LoginForm(forms.Form):
    email=forms.EmailField(required=True,widget=forms.EmailInput(attrs={"placeholder":"Enter your Email..."}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Enter yor password..."}))


# Signup form for the user
class SignupForm(forms.Form):
    email=forms.EmailField(required=True, widget=forms.EmailInput(attrs={"placeholder":"Enter your Email..."}))
    name=forms.CharField(label=None, widget=forms.TextInput(attrs={"placeholder":"Enter your Name..."}))


# to create user
class CreateUserForm(forms.Form):
    confirm_password=forms.CharField(label=None,help_text="Confirm Password", widget=forms.PasswordInput(attrs={"placeholder":"Confirm your Password..."}))
    password=forms.CharField(label=None, widget=forms.PasswordInput(attrs={"placeholder":"Enter your Password..."}))


# form to update the user profile
class ProfileUpdateForm(forms.Form):
    name=forms.CharField(required=True)
    email=forms.EmailField(required=True)
    contact_no=forms.CharField(required=False)
    profile_picture=forms.ImageField(required=False,widget=forms.ClearableFileInput(attrs={"hidden":True}))
    
    # constructor with the user instance
    def __init__(self,user_instance:User,*args, **kwargs):
        self.user_instance=user_instance
        super().__init__(*args, **kwargs)
        
        
    def save(self):
        # Update the user profile with the form data
        self.user_instance.name = self.cleaned_data["name"]
        self.user_instance.email = self.cleaned_data["email"]
        self.user_instance.contact_no = self.cleaned_data["contact_no"]

        if self.cleaned_data["contact_no"]:
            self.user_instance.contact_no = self.cleaned_data["contact_no"]

        if self.cleaned_data["profile_picture"]:
            self.user_instance.profile_picture = self.cleaned_data["profile_picture"]

        self.user_instance.save()
    

api/views/users_view.py
# importing typing
from typing import Any,List
# importing os and settings
import os
from marketmate.settings import BASE_DIR

# importing API view
from rest_framework.views import APIView

# importing request, response and status
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework import status

import os
from marketmate.settings import BASE_DIR

from django.contrib.auth import authenticate

from rest_framework_simplejwt.tokens import AccessToken

# importing model
from users.models import User
from listings.models import Listing,ListingImages

# importing serializers
from ..serializer import (UserRegistrationSerializer,GenerateTokenSerializer,
                          UpdateProfileSerializer)
from ..serializer import FetchListingSerializer,FetchListingImagesSerializer,FetchUserSerializer

# for JWT authentication
from ..jwt_authetication import authenticate_jwt

from marketmate.gcs_config import generate_signed_url,upload_file,delete_file

class UserApiView(APIView):
    # --------------GET------------------
    # to fetch all the users
    # only for admin
    @authenticate_jwt
    def get(self,req:Request, id:Any=None)->Response:
        try:
            # if the user is not the admin
            if not req.user.is_superuser:
                return Response({"messages":["Unauthorized!"]},status=status.HTTP_401_UNAUTHORIZED) 
            query=req.GET.get("listings")
            # if the users to be fetched with the listings
            if query and query=="True":
                return self.get_with_listings(req=req,id=id)
            return self.get_users_without_listings(req)


        except Exception:
            return Response({"message":["Internal Server error "]},status=status.HTTP_500_INTERNAL_SERVER_ERROR)
    # to fetch all the users with the listings 
    def get_with_listings(self,req:Request,id:Any=None)->Response:
        try:
            data=[]
            users=User.objects.all()
            # if no user found
            if not users:
                return Response({"data":data,"message":["No user found!"]},status=status.HTTP_404_NOT_FOUND)

            # to map the listing item with the users
            for user in users:
                user_serializer=FetchUserSerializer(user)
                user_data=user_serializer.data
                if user_data["profile_picture"]:
                    user_data["profile_picture"]=generate_signed_url(user_data["profile_picture"])
                user_data["listings"]=self.get_listings(user)
                data.append(user_data)
            
            return Response({"data":data,"message":["Users with listings fetched successfully "]},status=status.HTTP_200_OK)
            

        except Exception as e:
            return Response({"message":["Internal Server error "]},status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    # to fetch the listings from the database associated with a user
    def get_listings(self,user:User)->List[dict]:
        listings=[]
        items=Listing.objects.filter(user_id=user)
        for item in items:
            images=ListingImages.objects.filter(item_id=item)
            item_serializer=FetchListingSerializer(item)
            images_serializer=FetchListingImagesSerializer(images,many=True)
            item_data=item_serializer.data
            item_images=images_serializer.data
            for image in item_images:
                image["image"]=generate_signed_url(image["image"])

            item_data["images"]=images_serializer.data
            listings.append(item_data)
        
        return listings
    

    # to get all the users without the listings
    def get_users_without_listings(self,req:Request)->Response:
        try:
            users=User.objects.all()
            # if no user found
            if not users:
                return Response({"message":["No user found!"]},status=status.HTTP_404_NOT_FOUND)
            
            serialized_user=FetchUserSerializer(users,many=True)
            users_data=serialized_user.data
            if users_data["profile_picture"]:
                users_data["profile_picture"]=generate_signed_url(users_data["profile_picture"])
            return Response({"data":users_data,"message":["Users with listings fetched successfully "]},status=status.HTTP_200_OK)
            

        except Exception as e:
            return Response({"message":["Internal Server error "]},status=status.HTTP_500_INTERNAL_SERVER_ERROR)
        



    # ------------POST------------------
    # to create new user, or to generate authentication token
    def post(self,req:Request)->Response:
        if "create" in req.path:
            return self.create_user(req=req)
        elif "auth/generate-token" in req.path:
            return self.generate_token(req=req)

    # to create new user
    def create_user(self,req:Request)->Response:
        try:
            # to serialize the data
            serializer=UserRegistrationSerializer(data=req.data)
            # if the serialized data is valid
            if serializer.is_valid():
                name=serializer.validated_data["name"]
                email=serializer.validated_data["email"]
                password=serializer.validated_data["password"]
                # checking if the user already exists or not
                user=User.objects.filter(email=email).first()
                # if user exists
                if user:
                    return Response({"messages":["User already exists!"]} ,status=status.HTTP_400_BAD_REQUEST)
                
                # if the user does not exists, creating a new user
                new_user=User(email=email,name=name)
                new_user.set_password(raw_password=password)
                new_user.save()
                # if the user created successfully
                if new_user:
                    return Response({"user":{ "id":new_user.id,"name":new_user.name,"email":new_user.email,}
                                      ,"message":["User created successfully!"]},status=status.HTTP_201_CREATED)
                # if the user isn't created
                return Response({"message":["Unable to create user!"]},status=status.HTTP_503_SERVICE_UNAVAILABLE)

            # if the data isn't valid
            messages=[]
            for key,val in serializer.errors.items():
                if val[0].code.lower()=="required":
                    messages.append(f"{key}, {val[0]}")
                elif val[0].code.lower()=="invalid":
                    messages.append(val[0])
            return Response({"messages":messages},status=status.HTTP_400_BAD_REQUEST)
        
        # if something else went wrong
        except Exception as e:
            return Response({"message":["Internal Server error"]},status=status.HTTP_500_INTERNAL_SERVER_ERROR)
    
    # to generate the authentication token 
    def generate_token(self,req:Request)->Response:
        try:
            serializer=GenerateTokenSerializer(data=req.data)
            if serializer.is_valid():
                email=serializer.validated_data["email"]
                password=serializer.validated_data["password"]
                user=authenticate(email=email,password=password)
                if not user:
                    return Response({"messages":["Incorrect Email/Password"]},status=status.HTTP_401_UNAUTHORIZED)
                token=AccessToken()
                # including user id in the payload
                token["user_id"]=user.id
                return Response({"user":{ "id":user.id,"name":user.name, "email":user.email, },
                    "token":str(token),"messages":["Token generated"]}, status=status.HTTP_200_OK)
            
            messages=[]
            # for errors
            for key,val in serializer.errors.items():
                if val[0].code.lower()=="required":
                    messages.append(f"{key}, {val[0]}")
                elif val[0].code.lower()=="invalid":
                    messages.append(val[0])
            return Response({"messages":messages},status=status.HTTP_400_BAD_REQUEST)
        
        except Exception as e:
            return Response({"message":["Internal Server error"]},status=status.HTTP_500_INTERNAL_SERVER_ERROR)
    

    # ------------------PATCH-------------
    # to update user details, require authentication
    @authenticate_jwt 
    def patch(self, req:Request,id:Any=None)->Response:
        
        try:
            # if no id is provided, then the user want update its owm info
            if not id or req.user.id==id:
                user=req.user
                serializer=UpdateProfileSerializer(data=req.data)
                if serializer.is_valid():
                    validated_data=serializer.validated_data
                    if "name" in validated_data:
                        user.name=validated_data["name"]
                    if "email" in validated_data:
                        user.email=validated_data["email"]
                    if "profile_picture" in validated_data:
                        user.profile_picture=validated_data["profile_picture"]
                    if "contact_no" in validated_data:
                        user.contact_no=validated_data["contact_no"]
                    
                    user.save()
                    return Response({"user":{"id":user.id,"name":user.name},"messages":["User updated successfully"]},status=status.HTTP_202_ACCEPTED)
                # if there is error in serializer
                if serializer.errors:
                    messages=[]
                    for key, value in serializer.errors.items():
                        messages.append(f"{key}, {value}")
                    return Response({"messages":messages},status=status.HTTP_400_BAD_REQUEST)
                # if there is another issue
                return Response({"messages":["Unable to update user!"]},status=status.HTTP_400_BAD_REQUEST)

templates/users/_file_input_.html
<span class="clearable-file-input">
    <input type="{{ widget.type }}" name="{{ widget.name }}" accept="{{ widget.attrs.accept }}"
        class="clearablefileinput" id="{{ widget.id }}"{% if widget.is_required %} required{% endif %} {% if widget.is_disabled %}disabled{% endif %}>
    <label for="{{ widget.id }}">
        <span>{{ widget.attrs.placeholder }}</span>
    </label>
</span>

templates/users/create_user.html
{% extends "base.html" %}

{% load static %}

<!-- for title -->
{% block title %}
<title>Create Account | MM</title>
{% endblock title %}

<!-- for static -->
{% block static %}
<link rel="stylesheet" href="{% static "/css/signup.css" %}">
{% endblock static %}

<!-- content -->
{% block content %}

{% url "user_create_verify" token=token as create %}
<div class="root">
    <!-- signup form -->
    <form action="{{create}}" method="post">
        <p>Create Account | MM</p>
        {% csrf_token %}
        {{form.password}}
        {{form.confirm_password}}
        <input type="submit" class="submit-btn" value="Create Account">
    </form>
</div>
{% endblock content %}

templates/users/edit_profile.html
{% extends "base.html" %}

{% load static %}

<!-- for title -->
{% block title %}
<title>{{request.user.name}} | Edit Profile</title>
{% endblock title %}

<!-- for static -->
{% block static %}
<link rel="stylesheet" href="{% static "/css/edit_profile.css" %}">
{% endblock static %}

<!-- content -->
{% block content %}
<div class="root">

    {% url "user_update_profile" as update %}
    <form action="{{update}}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% comment %} {{form}} {% endcomment %}
        <p>Personal Info</p>
        {{ form.name.label_tag }} {{ form.name }}
        {{ form.email.label_tag }} {{ form.email }}
        <hr>
        <p>Contact Info</p>
        {{ form.contact_no.label_tag }} {{ form.contact_no }}
        <hr>
        <p>Profile Picture</p>
        {% comment %} {{ form.profile_picture.label_tag }} {% endcomment %}
        <label class="profile-pic-label" for="id_profile_picture">Select Picture</label>
        <p hidden>

            {{ form.profile_picture }}
        </p>
        <input type="submit" name="" class="submit-btn" value="Save Changes" id="">
    </form>
    {% if request.user.profile_picture %}
    <img src="{{request.user.profile_picture}}" class="user-profile-pic" alt="">
    {% endif %}

</div>
{% endblock content %}

templates/users/login.html
{% extends "base.html" %}

{% load static %}

<!-- for title -->
{% block title %}
<title>Login | MM</title>
{% endblock title %}

<!-- for static -->
{% block static %}
<link rel="stylesheet" href="{% static "/css/login.css" %}">
<script src="{% static " /js/login.js" %}" defer></script>
{% endblock static %}

<!-- content -->
{% block content %}
<div class="root">
    {% url "user_create_session" as create_session %}
    <form action="{{create_session}}" method="post">
        <p>Welcome to MM!</p>
        {% csrf_token %}
        {{loginForm.email}}
        {{loginForm.password}}
        <input type="submit" class="submit-btn" name="" id="" value="Log in">
    </form>
</div>
{% endblock content %}

templates/users/profile.html
{% extends "base.html" %}

{% load static %}

<!-- for title -->
{% block title %}
<title>{% if profile_user %}{{profile_user.name}} | Profie{% else %} {{request.user.name}} | Profie {% endif %}</title>
{% endblock title %}

<!-- for static -->
{% block static %}
    <link rel="stylesheet" href="{% static "/css/profile.css" %}">
    <script defer src="{% static "/js/profile.js" %}" ></script>
{% endblock static %}

<!-- content -->
{% block content %}
{% load currency_filter %}
    {% url "user_edit_profile" as edit_profile %}
    {% url "user_destroy_session" as logout %}
    <div class="root">
        <aside class="aside-section">
            <div class="profile">
                {% if profile_user %}
                <img src="{% if profile_user.profile_picture %} {{profile_user.profile_picture}}{% else %}{% static "/images/icons/profile-user.png" %}{% endif %}" alt="">
                <h2>{{profile_user.name}} </h2>
                {% else %}
                    <img src="{% if request.user.profile_picture %}{{request.user.profile_picture}}{% else %}{% static "/images/icons/profile-user.png" %}{% endif %}" alt="">
                    <h2>{{request.user.name}} </h2>
                    <a href="{{edit_profile}}">Edit Profile</a>
                    <a href="{{logout}}">Logout</a>
                {% endif %}
            </div>
            <div class="divider"></div>
        </aside>
        <main class="main-container">
            {% if listings %}
            
                {% for listing, image in listings.items %}
                    <div class="item-container" id="{{listing.id}}">
                        <img src="{% if image %}{{image.image}}{% else %}{% static "/images/icons/image.png" %} {% endif %}" id="{{listing.id}}" alt="">
                        <p class="title" id="{{listing.id}}" >{{listing.title}}</p>
                        <p class="price" id="{{listing.id}}" >{{listing.price | format_currency }} </p>
                    </div>
                {% endfor %}
            {% else %}
            <div class="nothing-to-show-label">
                <p >You haven't listed anything yet!</p>
            </div>
            {% endif %}
        </main>
    </div>

{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}

{% load static %}
{% url "singup" as signup %}

<!-- for title -->
{% block title %}
    <title>Sign Up | MM</title>
{% endblock title %}

<!-- for static -->
{% block static %}
    <link rel="stylesheet" href="{% static "/css/signup.css" %}">
    <script src="{% static "/js/signup.js" %}" ></script>
{% endblock static %}


<!-- content -->
{% block content %}
<div class="root">
    {% url "user_create" as create %}
    <form action="{{create}}" method="post">
        <p>Sign Up | MM</p>
        {% csrf_token %}
        {{signupForm.name}}
        {{signupForm.email}}
        {{signupForm.password}}
        {{signupForm.confirm_password}}
        <input type="submit" name="" id="" class="submit-btn" value="Sign up">
    </form>
</div>
{% endblock content %}